#!/usr/bin/env zsh

dotfiles_path=$HOME/ansible/dotfiles # todo pass path
target_dir=$HOME

# Check if the param passed is correct
if [[ $(dirname "$0") -ef $dotfiles_path ]]
then
   echo "dotfiles_path Looks Good"
else
   echo "dotfiles_path seems incorrect, abort!!"
   echo $dotfiles_path
   exit 1
fi

# GOTO Dotfiles path to run stow
pushd $dotfiles_path

# Some of these files may already exist, in that case
# manually delete them. TODO figure out way to delete
rm -f ~/.zshrc
rm -f ~/.gitconfig
rm -f ~/.gitignore

# nvim is usually clean, this is not needed
# rm -f ~/.config/nvim

# sublime text, remove autogenerated .DS_Store files
find ~/Library/Application\ Support/Sublime\ Text -name ".DS_Store" -delete
find . -name ".DS_Store" -delete
rm -rf ~/Library/Application\ Support/Sublime\ Text/Packages/User


# dotfile configs
vector=(
	zsh
	git 
	sublime 
	nvim
)

for folder in $vector
do
	stow -D $folder --target=$target_dir
	stow $folder --target=$target_dir
done

# Done go back to wherever you came from
popd