#!/usr/bin/env ansible-playbook
- hosts: localhost
  connection: local
  # become: true

  vars:
    sublime_base_path: "~/Library/Application Support/Sublime Text"

  tasks:
  - debug:
      msg: Check we are running in the directory of the script
    failed_when: not ansible_env.PWD.endswith('/ansible')

  # Plays
  # - name: Install Homebrew Packages
  #   import_tasks: tasks/homebrew-packages.yml 

  # - name: Install ZSH shell
  #   import_tasks: tasks/setup-zsh.yml  

  # - name: OSX Defaults
  #   import_tasks: tasks/osx-defaults.yml