#!/usr/bin/env ansible-playbook
- hosts: localhost
  connection: local
  # become: true

  vars:
    sublime_base_path: "~/Library/Application Support/Sublime Text"
    dotfiles_path: "~/ansible/dotfiles"

  tasks:
  - debug:
      msg: Check we are running in the directory of the script
    failed_when: not ansible_env.PWD.endswith('/ansible')

  - name: Execute shell script that stows all symlinks
    ansible.builtin.shell:
      cmd: find . -name ".DS_Store" -delete


  # Plays
  - name: Install Homebrew Packages
   import_tasks: tasks/homebrew-packages.yml 

  - name: OSX Defaults
   import_tasks: tasks/osx-defaults.yml

  - name: Install all things terminal
    import_tasks: tasks/setup-terminal.yml  

  - name: Execute shell script that stows all symlinks
    ansible.builtin.shell:
      cmd: sh ./dotfiles/install.sh

