- debug:
    msg: Before Setup-zsh, Check if we are running in the directory of the script
  failed_when: not ansible_env.PWD.endswith('/.ansible')


# Clean Oh My ZSH directory
- name: Install Oh My ZSH
  ansible.builtin.shell:
    cmd: rm -rf ~/.oh-my-zsh

# Install Oh My ZSH Directory
- name: Install Oh My ZSH
  ansible.builtin.shell:
    cmd: sh -c "$(curl -fsSL https://raw.github.com/ohmyzsh/ohmyzsh/master/tools/install.sh)"

# Install plugins
- name: Install zsh-autosuggestions
  ansible.builtin.shell:
    cmd: git clone https://github.com/zsh-users/zsh-autosuggestions ${ZSH_CUSTOM:-~/.oh-my-zsh/custom}/plugins/zsh-autosuggestions

- name: Install zsh-syntax-highlighting
  ansible.builtin.shell:
    cmd: git clone https://github.com/zsh-users/zsh-syntax-highlighting.git ${ZSH_CUSTOM:-~/.oh-my-zsh/custom}/plugins/zsh-syntax-highlighting


# # Setup .zshrc file
# - name: .zshrc config
#   copy:
#     src: dotfiles/.zshrc
#     dest: ~/.zshrc
